version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    environment:
      PASS: true
    steps:
      - checkout
      - restore_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - home/circleci/.yarn
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build Dist Folder
          command: yarn build

  deploy:
    docker:
      - image: circleci/python:3
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync dist/ s3://mentorship-htmltime --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master